In [14]:
import torch

In [15]:
inputs = torch.randn(6, 3)

In [16]:
query = inputs[1]

In [17]:
attn_scores = torch.empty(inputs.shape[0])

In [18]:
for i, x_i in enumerate(inputs):
    attn_scores[i] = torch.dot(query, x_i)

In [19]:
attn_scores

tensor([ 1.7235,  1.7504,  0.3208, -1.1579,  0.4826, -2.2256])

In [24]:
(attn_scores / attn_scores.sum())

tensor([ 1.9282,  1.9584,  0.3589, -1.2954,  0.5399, -2.4900])

In [31]:
torch.exp(attn_scores)/torch.sum(torch.exp(attn_scores))

tensor([0.3791, 0.3895, 0.0932, 0.0213, 0.1096, 0.0073])